apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: mypod
      labels:
        env: dev
    spec:
      containers:
	 - name: evertz01
	   image: atulsh1140/kubernetes_pipeline
	   imagePullPolicy: Always
           ports:
           - containerPort: 80
